services:
  router1:
    image: osrg/gobgp
    entrypoint: ["/go/bin/gobgpd", "-f", "/etc/gobgp/gobgp.yaml"]
    volumes:
      - ./router1/gobgp.yaml:/etc/gobgp/gobgp.yaml
    networks:
      net-router1:
        ipv4_address: 172.20.0.254
      net-core:
        ipv4_address: 172.20.3.4

  router2:
    image: osrg/gobgp
    entrypoint: ["/go/bin/gobgpd", "-f", "/etc/gobgp/gobgp.yaml"]
    volumes:
      - ./router2/gobgp.yaml:/etc/gobgp/gobgp.yaml
    networks:
      net-router2:
        ipv4_address: 172.20.1.254
      net-core:
        ipv4_address: 172.20.3.2

  router3:
    image: osrg/gobgp
    entrypoint: ["/go/bin/gobgpd", "-f", "/etc/gobgp/gobgp.yaml"]
    volumes:
      - ./router3/gobgp.yaml:/etc/gobgp/gobgp.yaml
    networks:
      net-router3:
        ipv4_address: 172.20.2.254
      net-core:
        ipv4_address: 172.20.3.3

networks:
  net-router1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  net-router2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
  net-router3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
  net-core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
