version: "3"
services:
  router1:
    image: osrg/gobgp
    container_name: router1
    entrypoint: /go/bin/gobgpd
    command: -f /etc/gobgp/gobgp.yaml --config-type yaml
    volumes:
      - ./router1/gobgp.yaml:/etc/gobgp/gobgp.yaml
    networks:
      net1:
        ipv4_address: 172.28.0.11

  router2:
    image: osrg/gobgp
    container_name: router2
    entrypoint: /go/bin/gobgpd
    command: -f /etc/gobgp/gobgp.yaml --config-type yaml
    volumes:
      - ./router2/gobgp.yaml:/etc/gobgp/gobgp.yaml
    networks:
      net1:
        ipv4_address: 172.28.0.2

  router3:
    image: osrg/gobgp
    container_name: router3
    entrypoint: /go/bin/gobgpd
    command: -f /etc/gobgp/gobgp.yaml --config-type yaml
    volumes:
      - ./router3/gobgp.yaml:/etc/gobgp/gobgp.yaml
    networks:
      net1:
        ipv4_address: 172.28.0.3

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24