x-common-defaults: &common
  image: alpine
  stop_grace_period: 1s
  cap_add:
    - NET_ADMIN

services:
  router:
    <<: *common
    privileged: true
    command: ash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward && trap "exit" TERM; while true; do usleep 500000; done'
    container_name: router
    networks:
      net-router1:
        ipv4_address: 172.20.0.254
      net-router2:
        ipv4_address: 172.20.1.254
      net-router3:
        ipv4_address: 172.20.2.254
      net-core:
        ipv4_address: 172.20.3.254

  host1:
    <<: *common
    container_name: host1
    networks:
      net-router1:
        ipv4_address: 172.20.0.100
    command: ash -c 'ip route del default && ip route add default via 172.20.0.254 && trap "exit" TERM; while true; do usleep 500000; done'

  host2:
    <<: *common
    container_name: host2
    networks:
      net-router2:
        ipv4_address: 172.20.1.100
    command: ash -c 'ip route del default && ip route add default via 172.20.1.254 && trap "exit" TERM; while true; do usleep 500000; done'

  host3:
    <<: *common
    container_name: host3
    networks:
      net-router3:
        ipv4_address: 172.20.2.100
    command: ash -c 'ip route del default && ip route add default via 172.20.2.254 && trap "exit" TERM; while true; do usleep 500000; done'

networks:
  net-router1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

  net-router2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

  net-router3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24

  net-core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
