x-common-defaults: &common
  image: alpine
  stop_grace_period: 1s
  privileged: true
  cap_add:
    - NET_ADMIN

services:
  dns_server:
    <<: *common
    container_name: dns_server
    command: >
      ash -c '
        apk add --no-cache dnsmasq;
        echo "address=/host1/172.20.0.100" > /etc/dnsmasq.d/hosts.conf;
        echo "address=/host2/172.20.1.100" >> /etc/dnsmasq.d/hosts.conf;
        echo "address=/router1/172.20.0.254" >> /etc/dnsmasq.d/hosts.conf;
        echo "address=/router2/172.20.1.254" >> /etc/dnsmasq.d/hosts.conf;
        echo "address=/router1-core/172.20.3.101" >> /etc/dnsmasq.d/hosts.conf;
        echo "address=/router2-core/172.20.3.2" >> /etc/dnsmasq.d/hosts.conf;
        dnsmasq -k;
      '
    networks:
      net-router1:
        ipv4_address: 172.20.0.253
      net-router2:
        ipv4_address: 172.20.1.253
      net-core:
        ipv4_address: 172.20.3.253

  router1:
    <<: *common
    command: ash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward; ip route add 172.20.1.0/24 via 172.20.3.2; trap "exit" TERM; while true; do usleep 500000; done'
    container_name: router1
    networks:
      net-router1:
        ipv4_address: 172.20.0.254
        aliases:
          - router1
      net-core:
        ipv4_address: 172.20.3.101
        aliases:
          - router1-core
    dns:
      - 172.20.0.253 # Updated to new DNS server IP

  router2:
    <<: *common
    command:  ash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward; ip route add 172.20.0.0/24 via 172.20.3.101; trap "exit" TERM; while true; do usleep 500000; done'
    container_name: router2
    networks:
      net-router2:
        ipv4_address: 172.20.1.254
        aliases:
          - router2
      net-core:
        ipv4_address: 172.20.3.2
        aliases:
          - router2-core
    dns:
      - 172.20.1.253 # Updated to new DNS server IP

  host1:
    <<: *common
    container_name: host1
    command: ash -c 'sleep 1;ip route del default; ip route add default via 172.20.0.254; route; trap "exit" TERM; while true; do usleep 500000; done'
    networks:
      net-router1:
        ipv4_address: 172.20.0.100
        aliases:
          - host1
    dns:
      - 172.20.0.253 # Updated to new DNS server IP

  host2:
    <<: *common
    container_name: host2
    command: ash -c 'sleep 1;ip route del default; ip route add default via 172.20.1.254; route; trap "exit" TERM; while true; do usleep 500000; done'
    networks:
      net-router2:
        ipv4_address: 172.20.1.100
        aliases:
          - host2
    dns:
      - 172.20.1.253 # Updated to new DNS server IP
  host3:
    <<: *common
    container_name: host3
    command: ash -c 'route; trap "exit" TERM; while true; do usleep 500000; done'
    networks:
      net-router2:
        ipv4_address: 172.20.1.103
        aliases:
          - host3
    dns:
      - 172.20.1.253 # Updated to new DNS server IP


networks:
  net-router1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

  net-router2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

  net-core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24