x-common-defaults: &common
  image: alpine
  command: ash -c 'trap "exit" TERM; while true; do usleep 500000; done'
  stop_grace_period: 10s
  privileged: true
  cap_add:
    - NET_ADMIN

services:
  router1:
    <<: *common
    command: ash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward; ip route add 172.20.1.0/24 via 172.20.3.2; trap "exit" TERM; while true; do usleep 500000; done'
    container_name: router1
    networks:
      net-router1:
        ipv4_address: 172.20.0.254
      net-core:
        ipv4_address: 172.20.3.101

  router2:
    <<: *common
    command:  ash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward; ip route add 172.20.0.0/24 via 172.20.3.101; trap "exit" TERM; while true; do usleep 500000; done'
    container_name: router2
    networks:
      net-router2:
        ipv4_address: 172.20.1.254
      net-core:
        ipv4_address: 172.20.3.2

  host1:
    <<: *common
    container_name: host1
    command: ash -c 'sleep 1;ip route del default; ip route add default via 172.20.0.254; route; trap "exit" TERM; while true; do usleep 500000; done'
    networks:
      net-router1:
        ipv4_address: 172.20.0.100

  host2:
    <<: *common
    container_name: host2
    command: ash -c 'sleep 1;ip route del default; ip route add default via 172.20.1.254; route; trap "exit" TERM; while true; do usleep 500000; done'
    networks:
      net-router2:
        ipv4_address: 172.20.1.100


networks:
  net-router1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

  net-router2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

  net-core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
